import React from 'react'
import Head from 'next/head'
import Header from './../../blocks/Header/Header'
import Footer from '@/components/blocks/Footer/Footer'
import styles from './MainLayout.module.css'
import bck_layer from './../../../public/images/layers/bck.png'
interface MainLayoutProps{
  children : React.ReactNode , 
  pageTitle : string
}

function MainLayout({ children , pageTitle} : MainLayoutProps) {
  console.log(bck_layer)
  return (
    <>
       <Head>
        <title>{ pageTitle }</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Header />
      <section className={styles.main_layout} style={{background : `url(${bck_layer.src})`}}>
          <div className='content_limiter'>
              {children}
          </div>
      </section>
      <Footer />
    </>
  )
}

export default MainLayout